package SolidMaker.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Scene = 0;
  public static final int Shape = 1;
  public static final int Sphere = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xd267692584f34fa5L, 0xa7e9ebe8e59401a2L);
    builder.put(0x2da713e252aa6d00L, Scene);
    builder.put(0x2da713e252aa6cf3L, Shape);
    builder.put(0x2da713e252aa6cfdL, Sphere);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
